spring:
  application:
    name: testBankRest
  datasource:
    password: postgres
    url:
    username: postgres
    driver-class-name: org.postgresql.Driver
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update


jwt:
  secretKey: ${JWT_SECRET}